try {
    function abs(x){
if(x<0){
throw new console.log('execption created')
}

}
abs(-7)
} catch (error) {
    
    console.log('exception resolved')
}

// finally{
//     console.log('please define function before calling it')
// }